### PR TITLE
Add support for symfony 5

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Add support for symfony 5
```

### CODE REVIEW

**Comment by core23** [comment]
> The PHPUnit bridge could also be bumped to 5, if you feel up to it

Fixed

**Comment by core23** [comment]
Can you tag a new release @greg0ire ?

**Comment by greg0ire** [comment]
My automated tool says there is nothing to release… the PR was done on master :sweat_smile:

**Comment by greg0ire** [comment]
I cherry-picked, let's see if the build passes: https://github.com/sonata-project/SonataDatagridBundle/pull/206

**Comment by core23** [comment]
> I cherry-picked, let's see if the build passes: #206

Oh, you're right 😅 Thanks

**Pull request merged**
