### PR TITLE
Fix tests for PHP 7.4

### PR DESCRIPTION
**Pull request by franmomu**
Some other findings while trying to fix tests in https://github.com/sonata-project/SonataAdminBundle/pull/5787

### CODE REVIEW

**Comment by greg0ire** [comment]
Might fix #204

**Comment by greg0ire** [comment]
Thanks @franmomu !

**Comment by franmomu** [comment]
> Might fix #204

it should!

**Comment by greg0ire** [comment]
Are you sure this should be labelled pedantic? You changed code in `src`, and fixed php 7.4 compatibility IMO.

**Comment by franmomu** [comment]
> Are you sure this should be labelled pedantic? You changed code in `src`, and fixed php 7.4 compatibility IMO.

You're right, at first I thought it was about changing just tests... but it changed, updating the changelog.

**Comment by greg0ire** [comment]
Should I create a new release after this?

**Comment by franmomu** [comment]
> Should I create a new release after this?

It would be nice! and also of https://github.com/sonata-project/twig-extensions, but whenever you can.

**Pull request merged**
