### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by franmomu**
## Subject
I was going to [fix the config deprecation](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/871) in this bundle, but it looks like neither the Configuration class nor the Extension class are used, there are no services declared, so I guess it is better to just remove them.

I am targeting this branch, because is the one.

## Changelog

```markdown
### Removed
- Removed useless `Configuration` and `SonataDatagridExtension` class
```

### CODE REVIEW

**Comment by OskarStark** [comment]
Yep it would be a BC break, this is not possible, please provide the patch for the deprecation here too.
Thanks

**Comment by franmomu** [comment]
Ok, I will. But why is this BC? I thought it wouldn't because no configuration has been used in this bundle since the start, I seem to remember that DependencyInjection folder was mandatory for a bundle at the beginning of SF2, just asking to learn.

**Comment by greg0ire** [comment]
Yeah that's highly improbable though… but let's not take any chances, we don't know what crazy things people are up to.

**Comment by franmomu** [comment]
Makes sense, I thought the same that no one would extend those classes, but you are right, better safe than sorry.

**Pull request closed without merging**
