### PR TITLE
Adapt the pager requests to be compatible with Postgresql

### PR DESCRIPTION
**Pull request by jerome-fix**
This correction should correct this issue : https://github.com/sonata-project/SonataNewsBundle/issues/226

### CODE REVIEW

**Comment by jerome-fix** [comment]
Note : 
The Travis build could not complete due to an problematic connection with github.com : « fatal: unable to connect to github.com »

**Comment by Soullivaneuh** [comment]
@jerome-fix rebasing your PR should fix Travis.

**Comment by OskarStark** [comment]
ping @jerome-fix can you please rebase your PR?

**Comment by hugovandepol** [comment]
Could this please be merged? Thanks!

**Comment by OskarStark** [comment]
:+1: thank you @jerome-fix

**Pull request merged**
