### PR TITLE
[WIP] Edited datagrid to handle facets and search

### PR DESCRIPTION
**Pull request by Bladrak**

### CODE REVIEW

**Comment by OskarStark** [comment]
@Bladrak can you please rebase your PR?

**Comment by Bladrak** [comment]
@OskarStark this PR is kept for reference if someone wishes to work on implementing ES search on datagrid bundle, not sure that rebasing would be interesting.

**Comment by OskarStark** [comment]
ah ok, didn't know that!

Thank you for the information! :+1:

**Comment by Soullivaneuh** [comment]
@Bladrak The main branch is now 2.x. Could you please reopen your PR agains this branch? Thanks.

**Pull request closed without merging**
