### PR TITLE
Removed unused template

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this is a major change.

## Changelog

```markdown
### Removed
- Removed `Search/results.html.twig` template
```

## Subject

This template isn't used anywhere in this bundle.

### CODE REVIEW

**Comment by greg0ire** [comment]
LGTM

**Comment by OskarStark** [comment]
Maybe in the ecommerce bundle?

**Comment by core23** [comment]
Then we should move the template to the right place.

**Comment by OskarStark** [comment]
Yes, but I am not sure, I was just thinking about this, because of the `products` stuff in it

**Comment by OskarStark** [comment]
@Soullivaneuh stuck StyleCI build

**Comment by OskarStark** [comment]
did you check that @core23 ?

**Comment by core23** [comment]
Haven't found the template in the `ecommerce` source. So we can remove it 👍

**Comment by core23** [comment]
@Soullivaneuh StyleCi :(

**Comment by Soullivaneuh** [comment]
@core23 No need to comment each PR. Please ping me on Slack instead.

**Comment by greg0ire** [comment]
Thanks @core23 , tagging as pedantic…

**Pull request merged**
