### PR TITLE
Cleanup before 3.0.0

### PR DESCRIPTION
**Pull request by kunicmarko20**
After this, 3.0.0 has :+1: from me.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Why should we remove `\`? didn't we start adding them everywhere?

**Comment by greg0ire** [comment]
Not everywhere… some function will not benefit from a performance boost. The list is here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/548109f267a4cf783064c12512d8cd175d27b958/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L350

**Comment by greg0ire** [comment]
Almost there :P

**Comment by OskarStark** [comment]
Could you fixup the last two commits into one please? Afterwards good to merge 👍🏻✌🏻

**Comment by greg0ire** [comment]
@OskarStark why don't you squash merge?

**Comment by OskarStark** [comment]
I would like to keep 2 commits but if it’s not necessary please do

**Comment by greg0ire** [comment]
@OskarStark I did the fixup :)

**Comment by kunicmarko20** [comment]
But in the end, you are gonna squash merge and end up with 1 merge commit? Making it easier to revert later, what is the point of multiple commits in this case?

**Comment by OskarStark** [comment]
I would then use rebase and merge and keep the 2 commits, one additional thing is, that we could revert only the CS or the cleanup commit, but maybe it’s not worth here, so let’s merge it like it is

**Comment by OskarStark** [comment]
Ah great you did it, thanks @greg0ire

**Pull request merged**
